# Generated by Django 4.1.7 on 2023-02-23 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email",
            field=models.EmailField(default="", max_length=255),
        ),
    ]
