# Generated by Django 4.1.7 on 2023-02-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0007_alter_address_district_alter_address_house_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="district",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="house_number",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="province",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="road",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="sub_district",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="village",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="address",
            name="zip_code",
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_%(class)s",
                to="apis.address",
            ),
        ),
    ]
