# Generated by Django 4.1.7 on 2023-02-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0008_alter_address_district_alter_address_house_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_%(class)s",
                to="apis.address",
            ),
        ),
    ]
