# Generated by Django 4.1.7 on 2023-02-27 07:31

import apis.managers
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("apis", "0010_alter_address_district_alter_address_house_number_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apis.managers.UserSafeDeleteManager()),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_%(class)s",
                to="apis.address",
            ),
        ),
    ]
